import { ReactNode } from "react";
import { ChakraProvider } from "@chakra-ui/react"; 
import { ThemeProvider } from "./providers/themeProvider"; 
import "@/app/globals.css";

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the RootLayoutProps type
type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        {/* Wrap the children inside ChakraProvider for Chakra UI components */}
        <ChakraProvider>
          {/* Your custom ThemeProvider for managing theme switching */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
